### PR TITLE
Added 404 page with well designed UI

### LINKED ISSUE #30: Feature: Add 404 page
### Feature description

I want to add 404 page with well designed UI and with some appropriate information like we should inform the user that he has jumped or redirected to wrong page or the page he is trying to find is not available.

Please assign this issue to me under GSSOC '22.

Thanks!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rsinghcodes**
Fixes #30 

### 🖼️  404 Page Screenshot

Please review it and merge under **GSSoC'22**.

### CODE REVIEW

**Comment by khareyash05** [comment]
@rsinghcodes NIce work done! Can you show the screenshot for different screen sizes to check responsiveness

**Comment by rsinghcodes** [comment]
> @rsinghcodes NIce work done! Can you show the screenshot for different screen sizes to check responsiveness

Actually, this page is not responsive for mobile as IDE page is also not responsive, I checked it. Also, I think non-responsive IDE cannot be run using mobile.

So, I didn't focus on responsiveness but in future we can make it responsive.

**Review by irshadmd — APPROVED** [review]
looks good

**Comment by rsinghcodes** [comment]
@irshadmd Please put `level number` on it.

Thanks!

**Pull request merged**
