### PR TITLE
Improved the "public" directory with proper branding

### PR DESCRIPTION
**Pull request by tech-gunk**

### CODE REVIEW

**Review by khareyash05 — COMMENTED** [review]
Also add how to make a branch and basic git commands like git add . git commit , git push  in Contributing.md as since GSSOC aims at beginner friendly repositories.

**Review by irshadmd — CHANGES_REQUESTED** [review]
1. create a folder for images.
2. In CONTRIBUTING.md add steps to create a pull request.

**Comment by khareyash05** [comment]
LGTM!

**Review by irshadmd — APPROVED** [review]

**Review by khareyash05 — APPROVED** [review]
Nice work done!

**Review by irshadmd — APPROVED** [review]

**Comment by khareyash05** [comment]
image
@tech-gunk Resolve this errors and you are GTG!

**Pull request closed without merging**
