### PR TITLE
Add issue template Done 

### LINKED ISSUE #13: docs: Add Issue Templates
Chnages
Adding Issue templates
Template path  ``` .github/ISSUE_TEMPLATE ``` 
**Template Types**

156198784-b2e8d551-3df4-4aff-a7c7-051a88c344c0
156169861-53b91128-a1aa-4751-805e-affb8a4924a3

Contribution towards GSsoc`22, Thank you

### PR DESCRIPTION
**Pull request by maityamit**
Closes  #13 . 

**Changes :** 
- [x] 🐛 Bug Report Issue template done
- [x] 📄 Documentation Issue template done
- [x] 💡 Feature Issue template done

**Look the Changes :** 

3 Templates .. 

**1.  Bug Report Issue template**

**2. Documentation Issue template**

**3.  Feature Issue template**

- [x] I agree to follow this project's Code of Conduct . 

**Amit Maity** - GSSoC'22 Contributor.

### CODE REVIEW

**Comment by VaibhavPaliwal0007** [comment]
LGTM!

**Comment by maityamit** [comment]
@VaibhavPaliwal0007 
As per gssoc , you add lebel in this PR. 
GSSOC and what is the level of this PR , You can add .

**Comment by maityamit** [comment]
Hi , @irshadmd  there is another problem , 
You add wrong tag for that this PR not updates on GSSoC'22 Site . 
You Add - ``` GSSoC'22 ``` ``` level-1 ```
But as per official GSSoC'22 you need to add - ``` GSSoC22 ``` and ``` Level1 ``` . 

Only after that the score will update .

**Comment by irshadmd** [comment]
> 

updated

**Pull request merged**
