### PR TITLE
Download button

### PR DESCRIPTION
**Pull request by Aniket1026**

### CODE REVIEW

**Comment by irshadmd** [comment]
resolve the checks @Aniket1026

**Comment by Aniket1026** [comment]
@irshadmd sir ,can you please tell me how to resolve the checks as I have no idea abt the errors

**Comment by irshadmd** [comment]
> @irshadmd sir ,can you please tell me how to resolve the checks as I have no idea abt the errors
Screenshot 2022-04-14 at 6 21 21 PM

resolve these errors

**Comment by Aniket1026** [comment]
ok sir I've resolved the errors .

**Review by irshadmd — COMMENTED** [review]
Looks good now 🎉, just one thing download file with language extension

**Comment by Aniket1026** [comment]
ok sir I'll be working on this feature now .

**Comment by Aniket1026** [comment]
Thank you sir 🎉🎉. 
I'll be working on this feature now

**Comment by irshadmd** [comment]
> Thank you sir 🎉🎉. I'll be working on this feature now

great 🚀

**Comment by Aniket1026** [comment]
sir, with using frontend only I'm not able to do as you said language specific extensions while downloading. I'm not able to resolve this with using reactjs

**Comment by irshadmd** [comment]
> sir, with using frontend only I'm not able to do as you said language specific extensions while downloading. I'm not able to resolve this with using reactjs

try to get the value of the selected language

**Comment by Aniket1026** [comment]
Sir this contribution of mine is not showing in my GSSOC22 stats . Can you do something ? so that I can get more point
Thank you 😇

**Comment by irshadmd** [comment]
> Sir this contribution of mine is not showing in my GSSOC22 stats . Can you do something ? so that I can get more point Thank you 😇

complete this issue first

**Comment by Aniket1026** [comment]
Ok sir I'm trying

**Comment by Aniket1026** [comment]
sir I'm unable to add the feature to download the code with file extension because I used blob and it doesn't have the feature to download with file extensions 😞

**Review by irshadmd — APPROVED** [review]

**Pull request merged**
