### PR TITLE
ComponentsAdded

### PR DESCRIPTION
**Pull request by ayush25102001**
Login/Register Buttons
Screenshot (40)

Login Form
Screenshot (41)

SignUp Form
Screenshot (42)

### CODE REVIEW

**Comment by ayush25102001** [comment]
> > > this is not looking good, open a modal on the login button click.
> > 
> > 
> > Means do u want just one button available on the header I.e login which on being clicked renders the login component along with option to signUp
> 
> yes

Any corrections on the form or button UI

**Comment by ayush25102001** [comment]
Screenshot (43)
Screenshot (44)
@irshadmd

**Comment by irshadmd** [comment]
@ayush25102001 I told you to use Modal

**Comment by irshadmd** [comment]
@ayush25102001 any update?

**Comment by ayush25102001** [comment]
> @ayush25102001 any update?

Sir I am working on it,I require some more time.

**Comment by irshadmd** [comment]
> > @ayush25102001 any update?
> 
> Sir I am working on it,I require some more time.

Okay, try to finish fast.

**Comment by ayush25102001** [comment]
@irshadmd sir,I tried this but I am not able to add the models on buttonclick.

**Pull request closed without merging**
