### PR TITLE
Download Button Added

### PR DESCRIPTION
**Pull request by aparna-bhatt**

### CODE REVIEW

**Comment by irshadmd** [comment]
resolve this error 
image

**Comment by aparna-bhatt** [comment]
I have resolved the issue please see to it.

**Comment by irshadmd** [comment]
@aparna-bhatt resolve conflicts

**Review by khareyash05 — APPROVED** [review]

**Review by khareyash05 — APPROVED** [review]
Just resolve merge conflicts and you are GTG!

**Pull request merged**
