### PR TITLE
Added responsiveness to the IDE 

### PR DESCRIPTION
**Pull request by Ardent10**
Added responsiveness to the page, made theme toggle better.
Demo: [demo](https://drive.google.com/file/d/1tqhh5myjmXywLpL37gJE1McYNuI01SDU/view?usp=sharing)

### CODE REVIEW

**Review by irshadmd — APPROVED** [review]
LGTM🚀

**Comment by kumar-tushar** [comment]
@Ardent10 
There is no default code coming in your preview.

**Comment by irshadmd** [comment]
> @Ardent10 There is no default code coming in your preview for any language

You can create a new issue if you like to work on this

**Comment by Ardent10** [comment]
> @Ardent10 There is no default code coming in your preview for any language

This is probably because the fork I made was before integrating the backend in this codebase.

**Comment by VaibhavPaliwal0007** [comment]
Lgtm!

**Review by VaibhavPaliwal0007 — APPROVED** [review]

**Pull request merged**
